// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: life.proto

package life

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── Requête : rectangle à afficher ──────────────────────────────────────────
type ViewportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewX         int32                  `protobuf:"varint,1,opt,name=view_x,json=viewX,proto3" json:"view_x,omitempty"` // coin X (0 ≤ x < 500)
	ViewY         int32                  `protobuf:"varint,2,opt,name=view_y,json=viewY,proto3" json:"view_y,omitempty"` // coin Y (0 ≤ y < 500)
	ViewW         int32                  `protobuf:"varint,3,opt,name=view_w,json=viewW,proto3" json:"view_w,omitempty"` // largeur  (≤ 500)
	ViewH         int32                  `protobuf:"varint,4,opt,name=view_h,json=viewH,proto3" json:"view_h,omitempty"` // hauteur  (≤ 500)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewportRequest) Reset() {
	*x = ViewportRequest{}
	mi := &file_life_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewportRequest) ProtoMessage() {}

func (x *ViewportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_life_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewportRequest.ProtoReflect.Descriptor instead.
func (*ViewportRequest) Descriptor() ([]byte, []int) {
	return file_life_proto_rawDescGZIP(), []int{0}
}

func (x *ViewportRequest) GetViewX() int32 {
	if x != nil {
		return x.ViewX
	}
	return 0
}

func (x *ViewportRequest) GetViewY() int32 {
	if x != nil {
		return x.ViewY
	}
	return 0
}

func (x *ViewportRequest) GetViewW() int32 {
	if x != nil {
		return x.ViewW
	}
	return 0
}

func (x *ViewportRequest) GetViewH() int32 {
	if x != nil {
		return x.ViewH
	}
	return 0
}

// ── Éléments de jeu ─────────────────────────────────────────────────────────
type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_life_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_life_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_life_proto_rawDescGZIP(), []int{1}
}

func (x *Cell) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Cell) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    int32                  `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Alive         []*Cell                `protobuf:"bytes,2,rep,name=alive,proto3" json:"alive,omitempty"`
	SentUnixns    int64                  `protobuf:"varint,3,opt,name=sent_unixns,json=sentUnixns,proto3" json:"sent_unixns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_life_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_life_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_life_proto_rawDescGZIP(), []int{2}
}

func (x *Board) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Board) GetAlive() []*Cell {
	if x != nil {
		return x.Alive
	}
	return nil
}

func (x *Board) GetSentUnixns() int64 {
	if x != nil {
		return x.SentUnixns
	}
	return 0
}

var File_life_proto protoreflect.FileDescriptor

const file_life_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"life.proto\x12\x04life\"m\n" +
	"\x0fViewportRequest\x12\x15\n" +
	"\x06view_x\x18\x01 \x01(\x05R\x05viewX\x12\x15\n" +
	"\x06view_y\x18\x02 \x01(\x05R\x05viewY\x12\x15\n" +
	"\x06view_w\x18\x03 \x01(\x05R\x05viewW\x12\x15\n" +
	"\x06view_h\x18\x04 \x01(\x05R\x05viewH\"\"\n" +
	"\x04Cell\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"j\n" +
	"\x05Board\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x05R\n" +
	"generation\x12 \n" +
	"\x05alive\x18\x02 \x03(\v2\n" +
	".life.CellR\x05alive\x12\x1f\n" +
	"\vsent_unixns\x18\x03 \x01(\x03R\n" +
	"sentUnixns2B\n" +
	"\n" +
	"GameOfLife\x124\n" +
	"\fStreamBoards\x12\x15.life.ViewportRequest\x1a\v.life.Board0\x01B(Z&github.com/ugora/gameoflife/proto;lifeb\x06proto3"

var (
	file_life_proto_rawDescOnce sync.Once
	file_life_proto_rawDescData []byte
)

func file_life_proto_rawDescGZIP() []byte {
	file_life_proto_rawDescOnce.Do(func() {
		file_life_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_life_proto_rawDesc), len(file_life_proto_rawDesc)))
	})
	return file_life_proto_rawDescData
}

var file_life_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_life_proto_goTypes = []any{
	(*ViewportRequest)(nil), // 0: life.ViewportRequest
	(*Cell)(nil),            // 1: life.Cell
	(*Board)(nil),           // 2: life.Board
}
var file_life_proto_depIdxs = []int32{
	1, // 0: life.Board.alive:type_name -> life.Cell
	0, // 1: life.GameOfLife.StreamBoards:input_type -> life.ViewportRequest
	2, // 2: life.GameOfLife.StreamBoards:output_type -> life.Board
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_life_proto_init() }
func file_life_proto_init() {
	if File_life_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_life_proto_rawDesc), len(file_life_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_life_proto_goTypes,
		DependencyIndexes: file_life_proto_depIdxs,
		MessageInfos:      file_life_proto_msgTypes,
	}.Build()
	File_life_proto = out.File
	file_life_proto_goTypes = nil
	file_life_proto_depIdxs = nil
}
